fragment PostParts on Post {
  __typename
  title
  slug
  date
  status
  category
  tags
  excerpt
  featured_image
  featured_image_alt
  focus_keyword
  seo_title
  seo_description
  body
}

fragment HomePageParts on HomePage {
  __typename
  hero_title
  hero_tagline
  intro_bio
}

fragment AboutPageParts on AboutPage {
  __typename
  hero_tagline
  bio_paragraphs
  pillars {
    __typename
    label
    title
    text
  }
}

fragment WritingPageParts on WritingPage {
  __typename
  header_title
  header_description
  topic_cards {
    __typename
    title
    description
    style
  }
}
